### ISSUE TITLE
[1.12.2]Tooltips will not be shown in JEI

### ISSUE THREAD

**Issue by SihenZhang** [Cazsius/Spice-of-Life-Carrot-Edition#42] opened 2018-12-17 13:58 UTC
Mod Version: 1.3.3
Forge Version: 14.23.5.2796
AppleCore Version: 3.1.4
JEI Version: 4.14.3.238
Description:
Tooltips will not be shown in JEI, but will be shown in the inventory normally.
Same issue in Spice of Life: https://github.com/squeek502/SpiceOfLife/issues/157
![](https://i.imgur.com/upVztpq.png)
![](https://i.imgur.com/KcEpFRK.png)

**Comment by juliand665** [comment] 2018-12-17 16:08
This is likely because (afaik) the tooltips shown in JEI are generated when the client starts, while the tooltips in the inventory obviously depend on the world you're currently in and are generated on the fly, so to speak.

**Comment by squeek502** [comment] 2018-12-17 20:22
Caused by https://github.com/mezz/JustEnoughItems/pull/1388

**Comment by squeek502** [comment] 2019-01-16 00:16
Will be fixed after the next version of JEI: https://github.com/mezz/JustEnoughItems/commit/6f191f65f1f2b55a095cb336f87b7f9487bb463b

**Comment by juliand665** [comment] 2019-01-16 00:43
I wonder if that'll also allow searching those tooltips, e.g. `#yet` to find foods you haven't tried yet, since I'd expect that search to be indexed on startup rather than asking all items for their tooltips upon searching…

**Closed as completed** 2019-01-26 21:10 UTC
