### ISSUE TITLE
Double tooltip

### ISSUE THREAD

**Issue by Toadby** [Cazsius/Spice-of-Life-Carrot-Edition#64] opened 2019-07-31 18:56 UTC
I am playing with Spice of Life: Carrot Edition, as well as the mod-name tooltip mod, and find that using both causes food items to render the mod/source name twice. This happens whether or not I have advanced tooltips enabled (initially I though that was the cause of the bug).
Game version 1.12.2

![Capture](https://user-images.githubusercontent.com/16440384/62239690-3c4c4180-b38a-11e9-9c8b-c734e53d3bdc.PNG)
![Capture2](https://user-images.githubusercontent.com/16440384/62239691-3ce4d800-b38a-11e9-93be-5db9e2eb77af.PNG)

**Comment by juliand665** [comment] 2019-08-01 11:55
Thanks for the report! Unfortunately, I was unable to reproduce this issue in an environment with just SoL: Carrot (+ its dependency AppleCore) and Mod Name Tooltip.

Does it still occur when you have only those mods enable? If not, try to figure out the addition of which mod causes it. Also, does this perhaps happen to non-food items as well?

**Comment by Toadby** [comment] 2019-08-01 19:23
Just in case there are multiple of the same mod, the Mod Name Tooltip mod I'm using is by Mezz. I also have Apple Skin installed. I have now somehow messed it up further so that the double tooltip displays on Every item... this may be Optfine?? I'm not sure. But I am still able to recreate the original error, where only food items are affected. I will create an instance with just SoL: Carrot, AppleCore, AppleSkin, and Mod Name Tooltip and get back to you!

**Comment by Toadby** [comment] 2019-08-01 19:28
I realize after writing that that this may be an issue with AppleSkin rather than SoL...... I will have to test! Sorry if that ends up being the case >_>

**Comment by Toadby** [comment] 2019-08-01 20:14
Was able to recreate the error with ApplCore, Hwyla, Mod Name Tooltip, and SOL: Carrot ! Removing SoL fixed it. I can't find anything in HWYLA settings to change tooltips....

**Comment by Toadby** [comment] 2019-08-01 20:19
Considering I also had an error with double tool tips on everything, I will consider writing to the Mod Name Tooltip author to see if they can fix both issues on their end. If I do that I will let you know, but I have to narrow down the mods involved and I don't feel like doing that right now.

**Comment by juliand665** [comment] 2019-08-20 17:20
Closing for now; feel free to reopen whenever you gain additional information :)

**Closed as completed by juliand665** 2019-08-20 17:20 UTC
Labels: invalid

**Comment by Toadby** [comment] 2019-08-20 22:47
Just realized it was an issue of feature overlap with Mod Name Tooltip and HWYLA. Unsure of why it was sometimes only affecting food items but it doesn't matter! :)

**Comment by juliand665** [comment] 2019-08-21 00:17
Ah, good to hear! Thanks for the effort <3
