### ISSUE TITLE
client connection crashing, MC 1.16.5

### ISSUE THREAD

**Issue by NoX-programer** [Cazsius/Spice-of-Life-Carrot-Edition#115] opened 2021-07-13 14:52 UTC
When player respawns at the bed (after death, after dragon win & return), client connection drops with
[connection crashed.txt](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/6809695/connection.crashed.txt)

Java v11
Minecraft v1.16.5
Forge v36.1.32
modpack Stacia Expert

But problem appears only with [mohist](https://wiki.mohistmc.com/#/) server core.

**Comment by juliand665** [comment] 2021-07-17 16:00
Thanks for the report! Some questions:
- Are you able to join back after this occurs?
- When you say it appears only with mohist, does that mean it doesn't happen if you run the server as a normal forge server without mohist?
- Does it still happen with just mohist and our mod?

**Comment by NoX-programer** [comment] 2021-07-18 02:17
* Yep. Right after that disconnect
* Correct - it is not appears with forge server core
* Yep, it happens when there is only your mod & mohist  ([server-console-error.txt](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/files/6835557/server-console-error.txt))
* And it not happens without any mods with mohist

**Comment by juliand665** [comment] 2021-07-18 04:23
Interesting. To me, this makes it pretty clear that this is an issue with mohist and not our mod. Mohist should behave just like regular forge to mods, and here it does not. It looks like it's not transferring capabilities to respawned players, at least not fast enough.

**Comment by NoX-programer** [comment] 2021-07-19 11:18
I'm already switched back to regular Forge (because not only of this one) so it' not a problem for me anymore, but, if you want to make your mod more widely compatible, you can dig deeper, debug and apply fix. Btw, mohist can be multithreaded server, and this can cause the issue.

**Comment by juliand665** [comment] 2021-07-19 17:47
I see. Well, thanks for making us aware, anyway! I'll go ahead and close this unless someone else complains, especially since I'd say the onus is on Mohist to fix this.

**Closed as completed by juliand665** 2021-07-19 17:47 UTC
Labels: mohist

**Comment by Column01** [comment] 2021-07-27 18:23
I too have this issue with Mohist + Spice of life. After looking at the player data, I assume the issue is because the food list is supposed to be reset on death (Since that's what it's configured to do) but it doesn't. Internally, SOL registers it as reset but it never actually happens, causing this issue.

**Comment by Column01** [comment] 2021-07-27 18:26
Should be noted it also happens after you go to eat again after the first rejoin

**Comment by Column01** [comment] 2021-07-27 18:42
Running `/foodlist clear` seems to fix it until you die again

**Comment by juliand665** [comment] 2021-07-27 20:32
Yeah, I'm leaving this closed because I'd say it's Mohist's fault—they should be behaving like vanilla; we shouldn't have to work around their shortcomings. Thanks for the research though!

**Comment by Romaindu35** [comment] 2021-07-31 20:37
This is a know bug with mohist and will be soon fix.
This bug is not related to this mod in particular, but to a modification of how forge works

**Comment by Ashley123477** [comment] 2021-12-28 00:04
i believe this is fixed on mohists end now, but i believe there is a new bug in mohist which resets all your previously eaten foods which in turn resets all your hearts

**Comment by juliand665** [comment] 2021-12-28 00:38
Thanks for the update! Nothing but issues with them, lol, but I get it—it's a complex undertaking.

**Comment by Ashley123477** [comment] 2021-12-28 00:39
Amazing software, just a ton of bugs to iron out :)
