### ISSUE TITLE
[Bug] Eating Pizza Crashes server

### ISSUE THREAD

**Issue by Akitori** [Cazsius/Spice-of-Life-Carrot-Edition#33] opened 2018-06-08 16:23 UTC
So uh, i'm using a mod called OverSaturation (basically gives full value of saturation and such)

I decided to try testing out the interactions between mods, and got this.

https://pastebin.com/czrW4FMW

This was after eating a pam's supreme pizza

**Comment by juliand665** [comment] 2018-06-08 17:44
Duplicate of #32

**Closed as completed by juliand665** 2018-06-08 17:44 UTC
Labels: duplicate
