### ISSUE TITLE
[1.12.2]  Wrong message when eating food

### ISSUE THREAD

**Issue by kwpugh** [Cazsius/Spice-of-Life-Carrot-Edition#10] opened 2017-09-30 23:08 UTC
Hi Folks,
 
I have the SOL Carrot mod on my MC 1.12.2/Forge/SpongeForge server.
 
I updated the config as follows:
# Configuration file
general {
# An array containing the milestones: How many unique foods you must eat to get the milestone bonus (defined above). Note that this represents the TOTAL number of foods needed; not the foods since the last milestone!
I:"Milestone amounts" <
10
20
30
40
50
60
70
80
90
100
>
# Number of hearts you spawn with. [range: 1 ~ 30, default: 10]
I:defaultHeartCount=10
# Number of hearts you gain per milestone. [range: 1 ~ 30, default: 2]
I:heartsPerMilestone=1
# Add tooltips to foods to indicate if they have been eaten? [default: true]
B:isFoodTooltipEnabled=true
}
 
I have a lot of foods in the pack, so I wanted 10 levels of earning extra hearts.
 
The progression of the eating works as intended, with the player getting an extra heart after eating 10 new foods.
 
However, the players recieve the following after eating ANY food: 
 "What a unique flavor!  You've gained a heart!  Sample another 10 varieties of food to gain another heart"
 
The results of the /sizefoodlist command shows the correct number of total foods eaten and the remaining number until next milestone.
 
Any ideas what might be wrong?
 
Regards

**Comment by LewisMcReu** [comment] 2017-10-09 18:08
To be clear, the message is appearing every time a food is eaten?

**Comment by LewisMcReu** [comment] 2017-10-09 18:10
Also, please use a codeblock when inserting config next time.

**Comment by kwpugh** [comment] 2017-10-09 18:22
Yes, every time.

Codeblock?

**Comment by LewisMcReu** [comment] 2017-10-09 18:32
there's a button in the text editor looking like this: < >

You can use it to prevent formatting of pieces of text, like this:

```
# Biggest
## Big
### Bigger
```
# Biggest
## Bigger
### Big

The hash causes headers to appear, and as such makes your issue comment look very confusing

**Comment by LewisMcReu** [comment] 2017-10-09 18:48
Well, did some testing and I'm not experiencing this problem. It might be SpongeForge interfering somehow with the eventhandling, although I'd doubt that. You're using the most recent version?

**Comment by kwpugh** [comment] 2017-10-09 19:05
I'm using in production:
Forge: 2503
SpongeForge: 2688
SoL Mod: 1.2.0

My test server is running Forge 2509 and SpongeForge 2696 and the error is still present.

**Comment by Cazsius** [comment] 2017-10-10 19:46
Marked as Invalid until can be replicated.

**Comment by GatorThing** [comment] 2018-03-18 23:52
Hi. I just had this same problem in a custom pack on a server running Sponge as well.

MC version 1.12.2
SoL:Carrot Version 1.12.1-1.2.0
SpongeForge Version 2931
Forge Version 14.23.2.2611

Have not changed default config, Gained 2 hearts at 5 foods eaten but also 6 and 7 when next set should be at 10.

**Comment by Cazsius** [comment] 2018-04-25 23:42
Still cannot replicate, closing due to inability to replicate

**Closed as completed by Cazsius** 2018-04-25 23:42 UTC
Labels: invalid

**Comment by bluelightning32** [comment] 2019-01-01 04:37
I'm hitting this. To reproduce it:
1. Install spongeforge with the solcarrot mod.
2. Connect with a client.
3. Eat new foods until one milestone is passed.
4. From there on, each eaten food (new or not) will print the message.

I've tried to investigate it with some log statements. The message is coming from the client, not the server. Every time the client gets the food eaten event, the player's max health is the old value again. It's like sponge forge isn't sending the client the right max health.
