### ISSUE TITLE
Internal server error (player kick) when eating anything after dying.

### ISSUE THREAD

**Issue by SSmileyV** [Cazsius/Spice-of-Life-Carrot-Edition#116] opened 2021-07-31 10:14 UTC
Title. It happenned multiple times and I don't really know how to fix it. Please, help me fixing this.
My server is running with MohistMC, it uses Forge and paper / bukkit / spigot as a base. The modlist pastebin is [here](https://pastebin.com/wcMFjyfm).
Here's the fragment where the error appears, the full log is above 15k lines, so I can't make a pastebin of it.
Thank you for helping me, let me know if you need something more.

<html>
<body>

[03:29:39] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Player must have food capability attached, but none was found.
--
11857 | Index: 1
11858 | Listeners:
11859 | 0: NORMAL
11860 | 1: ASM: class com.cazsius.solcarrot.tracking.FoodTracker onFoodEaten(Lnet/minecraftforge/event/entity/living/LivingEntityUseItemEvent$Finish;)V
11861 | 2: LOWEST
11862 | 3: ASM: class ovh.corail.tombstone.event.EventHandler onItemUseFinish(Lnet/minecraftforge/event/entity/living/LivingEntityUseItemEvent$Finish;)V
11863 | com.cazsius.solcarrot.tracking.FoodList$FoodListNotFoundException: Player must have food capability attached, but none was found.
11864 | at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:299)
11865 | at com.cazsius.solcarrot.tracking.FoodList.get(FoodList.java:24)
11866 | at com.cazsius.solcarrot.tracking.FoodTracker.onFoodEaten(FoodTracker.java:39)
11867 | at net.minecraftforge.eventbus.ASMEventHandler_309_FoodTracker_onFoodEaten_Finish.invoke(.dynamic)
11868 | at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
11869 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
11870 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
11871 | at net.minecraftforge.event.ForgeEventFactory.onItemUseFinish(ForgeEventFactory.java:325)
11872 | at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:3336)
11873 | at net.minecraft.entity.player.ServerPlayerEntity.func_71036_o(ServerPlayerEntity.java:1406)
11874 | at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:3216)
11875 | at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2567)
11876 | at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:251)
11877 | at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:528)
11878 | at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:296)
11879 | at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:242)
11880 | at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:142)
11881 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1055)
11882 | at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
11883 | at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:945)
11884 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760)
11885 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270)
11886 | at java.base/java.lang.Thread.run(Thread.java:829)

</body>
</html>

**Comment by juliand665** [comment] 2021-07-31 18:22
This is a duplicate of #115. It's Mohist's job to support Forge mods, not ours to work around Mohist's bugs.

**Closed as completed by juliand665** 2021-07-31 18:22 UTC
Labels: duplicate, mohist
